function generateGmail(name) {
  const cleanedName = name.toLowerCase().replace(/[^a-z0-9]/g, '');
  const randomNumber = Math.floor(100 + Math.random() * 9000); // 100 - 9999 পর্যন্ত
  const email = `${cleanedName}.autogenerated${randomNumber}@gmail.com`;
  return email;
}

export default generateGmail;
